### ISSUE TITLE
actions/checkout is run unnecessarily by this action

### ISSUE THREAD

**Issue by nemosupremo** [cookiecutter-openedx/aws-ecr-create#32]
**Describe the bug**
The action runs `actions/checkout`, duplicating checkout. It's not clear why this repo would even require checkout

**Workflow**
```yml
name: Example workflow

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # required antecedent
      - uses: actions/checkout@v1

      # required antecedent
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.THE_NAME_OF_YOUR_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.THE_NAME_OF_YOUR_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      # This action
      - name: Create an AWS ECR repository
        uses: openedx-actions/create-aws-ecr-repository
        with:
          aws-ecr-repository: my_new_repo
```

**Expected behavior**
`actions/checkout` is only run once, but it is run twice
